# Generated by Django 6.0.2 on 2026-02-08 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=50)),
                ('check_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('output', models.TextField(blank=True, null=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='inventory.host')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=50)),
                ('check_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=60)),
                ('timeout', models.IntegerField(default=10)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('last_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_checks', to='inventory.host')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'metric_name', 'timestamp'], name='monitoring__host_id_bf0624_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=50)),
                ('check_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('output', models.TextField(blank=True, null=True)),
                ('response_time', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='inventory.host')),
                ('service_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.servicecheckconfig')),
            ],
            options={
                'indexes': [models.Index(fields=['service_check', 'timestamp'], name='monitoring__service_547589_idx'), models.Index(fields=['host', 'check_type', 'check_name', 'timestamp'], name='monitoring__host_id_14b36d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SNMPDeviceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField(null=True)),
                ('value_string', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snmp_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.snmpdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['snmp_device', 'metric_name', 'timestamp'], name='monitoring__snmp_de_32beb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UPSMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=255)),
                ('metric_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ups_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inventory.upsdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['ups_device', 'metric_name', 'timestamp'], name='monitoring__ups_dev_dd10db_idx')],
            },
        ),
    ]
