# Generated by Django 6.0.2 on 2026-09-05 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet', models.CharField(help_text='CIDR subnet to scan (e.g., 192.168.1.0/24)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_hosts', models.IntegerField(default=0)),
                ('scanned_hosts', models.IntegerField(default=0)),
                ('found_hosts', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('os_guess', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ignored', 'Ignored'), ('added', 'Added')], default='new', max_length=20)),
                ('open_ports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_hosts', to='discovery.discoveryscan')),
            ],
            options={
                'unique_together': {('scan', 'ip_address')},
            },
        ),
    ]
