# Generated by Django 6.0.2 on 2026-02-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_auth_protocol',
            field=models.CharField(choices=[('MD5', 'MD5'), ('SHA', 'SHA')], default='MD5', max_length=10),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_priv_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_priv_protocol',
            field=models.CharField(choices=[('DES', 'DES'), ('AES', 'AES')], default='DES', max_length=10),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_security_level',
            field=models.CharField(choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], default='noAuthNoPriv', max_length=20),
        ),
        migrations.AddField(
            model_name='snmpdevice',
            name='snmp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_auth_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_auth_protocol',
            field=models.CharField(choices=[('MD5', 'MD5'), ('SHA', 'SHA')], default='MD5', max_length=10),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_priv_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_priv_protocol',
            field=models.CharField(choices=[('DES', 'DES'), ('AES', 'AES')], default='DES', max_length=10),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_security_level',
            field=models.CharField(choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], default='noAuthNoPriv', max_length=20),
        ),
        migrations.AddField(
            model_name='upsdevice',
            name='snmp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
