# Generated by Django 6.0.2 on 2026-02-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_snmpdevice_snmp_auth_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom name for dashboard display', max_length=255, null=True),
        ),
    ]
