# Generated by Django 6.0.2 on 2026-02-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_host_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC Address in XX:XX:XX:XX:XX:XX format', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Uplink device (e.g. Switch, Gateway, AP)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.host'),
        ),
        migrations.AddField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, help_text='Device Vendor (e.g. Apple, Ubiquiti)', max_length=255, null=True),
        ),
    ]
