# Generated by Django 6.0.3 on 2026-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_host_mac_address_host_parent_host_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='apple_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='device_class',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='identification_clues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='host',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='mdns_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DeviceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, db_index=True, max_length=17, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('mdns_name', models.CharField(blank=True, max_length=255, null=True)),
                ('apple_model', models.CharField(blank=True, max_length=255, null=True)),
                ('device_class', models.CharField(blank=True, max_length=64, null=True)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('identification_clues', models.JSONField(blank=True, default=list)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor_source', models.CharField(blank=True, max_length=64, null=True)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_network', models.CharField(blank=True, max_length=64, null=True)),
                ('sighting_count', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip_address',), name='uniq_device_observation_ip')],
            },
        ),
    ]
