# Generated by Django 6.0.2 on 2026-02-12 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_snmpdevice_snmp_auth_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_mac', models.CharField(blank=True, help_text='MAC address of target if unknown', max_length=17, null=True)),
                ('target_ip', models.GenericIPAddressField(blank=True, help_text='IP address of target if unknown', null=True)),
                ('target_interface', models.CharField(blank=True, help_text='Interface on target device', max_length=255, null=True)),
                ('source_interface', models.CharField(blank=True, help_text='Interface on source device', max_length=255, null=True)),
                ('link_type', models.CharField(choices=[('physical', 'Physical'), ('logical', 'Logical'), ('wireless', 'Wireless'), ('virtual', 'Virtual')], default='physical', max_length=20)),
                ('protocol', models.CharField(choices=[('lldp', 'LLDP'), ('cdp', 'CDP'), ('ospf', 'OSPF'), ('arp', 'ARP'), ('static', 'Static'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('bandwidth', models.BigIntegerField(blank=True, help_text='Link speed in bps', null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='inventory.host')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_links', to='inventory.host')),
            ],
            options={
                'unique_together': {('source', 'target', 'source_interface', 'target_interface')},
            },
        ),
    ]
